Makefile: Remove unused folder
Fix the following yocto build issue:
ERROR: QA Issue: dpaa2-dce: Files/directories were installed but not
shipped in any package:
  /usr/sbin
Please set FILES such that these items are packaged. Alternatively if
they are unneeded, avoid installing them or delete them within
do_install.
dpaa2-dce: 1 installed and not shipped files. [installed-vs-shipped]

Signed-off-by: Zongchun Yu <zongchun.yu@nxp.com>